name: Go Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (if needed)
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t go-api .

      - name: Run tests with coverage
        run: |
          docker run --rm -v "$(pwd)/coverage:/app/go-api/coverage" \
          go-api sh -c "make test-cover &&        \
          cp ./coverage.html ./coverage/ &&       \
          cp ./coverage.out ./coverage/ &&        \
          go tool cover -func=./coverage/coverage.out"

      - name: Upload coverage to Codecov (public repo)
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage.out
          flags: unittests
          name: go-api-coverage
          fail_ci_if_error: true
