name: Go Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (if needed)
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t go-api .

      - name: Run tests with coverage
        run: |
          docker run --rm go-api           \
          -v "${{ github.workspace }}/coverage:/app/go-api/coverage"  \
          sh -c "make test-cover &&        \
          cp ./coverage.html ./coverage/ &&    \
          cp ./coverage.out ./coverage/ &&     \
          go tool cover -func=./coverage/coverage.out"
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./test/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
